server:
  port: 8080

spring:
  application:
    name: inventory-management-system

  datasource:
    url: jdbc:mysql://localhost:3307/inventory_management_system
    username: sakib
    password: 120316
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.flywaydb: INFO

jwt:
  secret-key: "mySecretKey-afdsjhaf-adkfjsha-askdjfhaj-adkjfhaf-asdfkjhajf-anhdkjfadshf-adfkjhajdf-asdlfjha-adskfjhadjsf-adfjhadf-adfkjhajf"
  access-token-expiration: 5m
  refresh-token-expiration: 3d

refresh-token:
  cleanup:
    cron: "0 0 * * * *"