package com.db_migration.auth.enums;

public enum PermissionCode {
    CREATE_PRODUCT, // PRODUCT_M
    UPDATE_PRODUCT, // PRODUCT_M
    DELETE_PRODUCT, // PRODUCT_M
    VIEW_PRODUCT, // CUSTOMER // PRODUCT_M // INVENTORY_M

    CREATE_CATEGORY, // PRODUCT_M
    UPDATE_CATEGORY, // PRODUCT_M
    DELETE_CATEGORY, // PRODUCT_M
    VIEW_CATEGORY, // CUSTOMER // PRODUCT_M // INVENTORY_M

    CREATE_CART, // CUSTOMER
    UPDATE_CART, // CUSTOMER
    DELETE_CART, // CUSTOMER
    VIEW_CART, // CUSTOMER

    CREATE_ORDER, // CUSTOMER
    UPDATE_ORDER, // ORDER_M
    DELETE_ORDER, // ORDER_M
    VIEW_ORDER, // CUSTOMER // ORDER_M

    MANAGE_INVENTORY, // INVENTORY_M
    VIEW_INVENTORY // INVENTORY_M
}
